[2025-11-01T17:15:50.057+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_csv_to_clickhouse.load_csv_to_clickhouse manual__2025-11-01T17:15:43.335978+00:00 [queued]>
[2025-11-01T17:15:50.095+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_csv_to_clickhouse.load_csv_to_clickhouse manual__2025-11-01T17:15:43.335978+00:00 [queued]>
[2025-11-01T17:15:50.097+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-11-01T17:15:50.192+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_csv_to_clickhouse> on 2025-11-01 17:15:43.335978+00:00
[2025-11-01T17:15:50.239+0000] {standard_task_runner.py:60} INFO - Started process 196 to run task
[2025-11-01T17:15:50.244+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'load_csv_to_clickhouse', 'load_csv_to_clickhouse', 'manual__2025-11-01T17:15:43.335978+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/load_to_clickhouse.py', '--cfg-path', '/tmp/tmpirjxh5z5']
[2025-11-01T17:15:50.251+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask load_csv_to_clickhouse
[2025-11-01T17:15:50.815+0000] {task_command.py:423} INFO - Running <TaskInstance: load_csv_to_clickhouse.load_csv_to_clickhouse manual__2025-11-01T17:15:43.335978+00:00 [running]> on host 4944221c0f0f
[2025-11-01T17:15:56.355+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_csv_to_clickhouse' AIRFLOW_CTX_TASK_ID='load_csv_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T17:15:43.335978+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T17:15:43.335978+00:00'
[2025-11-01T17:15:57.780+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_to_clickhouse.py", line 51, in load_csv_to_clickhouse
    client.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 376, in execute
    rv = self.process_insert_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 607, in process_insert_query
    rv = self.send_data(sample_block, data,
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 660, in send_data
    self.connection.send_data(block)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 688, in send_data
    self.block_out.write(block)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/streams/native.py", line 48, in write
    write_column(self.context, col_name, col_type, items,
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/columns/service.py", line 167, in write_column
    column.write_data(items, buf)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/columns/base.py", line 145, in write_data
    self._write_data(items, buf)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/columns/base.py", line 148, in _write_data
    prepared = self.prepare_items(items)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/columns/base.py", line 137, in prepare_items
    self.before_write_items(items, nulls_map=nulls_map)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/columns/datecolumn.py", line 84, in before_write_items
    item = date(item.year, item.month, item.day)
AttributeError: 'str' object has no attribute 'year'
[2025-11-01T17:15:57.888+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=load_csv_to_clickhouse, task_id=load_csv_to_clickhouse, execution_date=20251101T171543, start_date=20251101T171550, end_date=20251101T171557
[2025-11-01T17:15:57.923+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 21 for task load_csv_to_clickhouse ('str' object has no attribute 'year'; 196)
[2025-11-01T17:15:57.988+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T17:15:58.041+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
